final inCase500APIData = {
  "Global": {
    "NewConfirmed": 257886,
    "TotalConfirmed": 17849120,
    "NewDeaths": 5615,
    "TotalDeaths": 685038,
    "NewRecovered": 222627,
    "TotalRecovered": 10552934
  },
  "Countries": [
    {
      "Country": "Afghanistan",
      "CountryCode": "AF",
      "Slug": "afghanistan",
      "NewConfirmed": 35,
      "TotalConfirmed": 36710,
      "NewDeaths": 11,
      "TotalDeaths": 1283,
      "NewRecovered": 0,
      "TotalRecovered": 25509,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Albania",
      "CountryCode": "AL",
      "Slug": "albania",
      "NewConfirmed": 120,
      "TotalConfirmed": 5396,
      "NewDeaths": 4,
      "TotalDeaths": 161,
      "NewRecovered": 9,
      "TotalRecovered": 2961,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Algeria",
      "CountryCode": "DZ",
      "Slug": "algeria",
      "NewConfirmed": 556,
      "TotalConfirmed": 30950,
      "NewDeaths": 13,
      "TotalDeaths": 1223,
      "NewRecovered": 451,
      "TotalRecovered": 20988,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Andorra",
      "CountryCode": "AD",
      "Slug": "andorra",
      "NewConfirmed": 0,
      "TotalConfirmed": 925,
      "NewDeaths": 0,
      "TotalDeaths": 52,
      "NewRecovered": 0,
      "TotalRecovered": 807,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Angola",
      "CountryCode": "AO",
      "Slug": "angola",
      "NewConfirmed": 16,
      "TotalConfirmed": 1164,
      "NewDeaths": 2,
      "TotalDeaths": 54,
      "NewRecovered": 23,
      "TotalRecovered": 460,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Antigua and Barbuda",
      "CountryCode": "AG",
      "Slug": "antigua-and-barbuda",
      "NewConfirmed": 0,
      "TotalConfirmed": 91,
      "NewDeaths": 0,
      "TotalDeaths": 3,
      "NewRecovered": 0,
      "TotalRecovered": 67,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Argentina",
      "CountryCode": "AR",
      "Slug": "argentina",
      "NewConfirmed": 5241,
      "TotalConfirmed": 196543,
      "NewDeaths": 53,
      "TotalDeaths": 3596,
      "NewRecovered": 2719,
      "TotalRecovered": 86499,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Armenia",
      "CountryCode": "AM",
      "Slug": "armenia",
      "NewConfirmed": 291,
      "TotalConfirmed": 38841,
      "NewDeaths": 11,
      "TotalDeaths": 749,
      "NewRecovered": 560,
      "TotalRecovered": 29557,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Australia",
      "CountryCode": "AU",
      "Slug": "australia",
      "NewConfirmed": 0,
      "TotalConfirmed": 17280,
      "NewDeaths": 0,
      "TotalDeaths": 201,
      "NewRecovered": 221,
      "TotalRecovered": 10204,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Austria",
      "CountryCode": "AT",
      "Slug": "austria",
      "NewConfirmed": 82,
      "TotalConfirmed": 21212,
      "NewDeaths": 0,
      "TotalDeaths": 718,
      "NewRecovered": 153,
      "TotalRecovered": 18911,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Azerbaijan",
      "CountryCode": "AZ",
      "Slug": "azerbaijan",
      "NewConfirmed": 279,
      "TotalConfirmed": 32157,
      "NewDeaths": 6,
      "TotalDeaths": 454,
      "NewRecovered": 592,
      "TotalRecovered": 26474,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Bahamas",
      "CountryCode": "BS",
      "Slug": "bahamas",
      "NewConfirmed": 25,
      "TotalConfirmed": 599,
      "NewDeaths": 0,
      "TotalDeaths": 14,
      "NewRecovered": 0,
      "TotalRecovered": 91,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Bahrain",
      "CountryCode": "BH",
      "Slug": "bahrain",
      "NewConfirmed": 208,
      "TotalConfirmed": 41190,
      "NewDeaths": 0,
      "TotalDeaths": 147,
      "NewRecovered": 371,
      "TotalRecovered": 38211,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Bangladesh",
      "CountryCode": "BD",
      "Slug": "bangladesh",
      "NewConfirmed": 2199,
      "TotalConfirmed": 239860,
      "NewDeaths": 21,
      "TotalDeaths": 3132,
      "NewRecovered": 1117,
      "TotalRecovered": 136253,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Barbados",
      "CountryCode": "BB",
      "Slug": "barbados",
      "NewConfirmed": 12,
      "TotalConfirmed": 122,
      "NewDeaths": 0,
      "TotalDeaths": 7,
      "NewRecovered": 2,
      "TotalRecovered": 98,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Belarus",
      "CountryCode": "BY",
      "Slug": "belarus",
      "NewConfirmed": 138,
      "TotalConfirmed": 67946,
      "NewDeaths": 4,
      "TotalDeaths": 563,
      "NewRecovered": 242,
      "TotalRecovered": 62686,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Belgium",
      "CountryCode": "BE",
      "Slug": "belgium",
      "NewConfirmed": 651,
      "TotalConfirmed": 69402,
      "NewDeaths": 4,
      "TotalDeaths": 9845,
      "NewRecovered": 27,
      "TotalRecovered": 17573,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Belize",
      "CountryCode": "BZ",
      "Slug": "belize",
      "NewConfirmed": 8,
      "TotalConfirmed": 56,
      "NewDeaths": 0,
      "TotalDeaths": 2,
      "NewRecovered": 0,
      "TotalRecovered": 30,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Benin",
      "CountryCode": "BJ",
      "Slug": "benin",
      "NewConfirmed": 0,
      "TotalConfirmed": 1805,
      "NewDeaths": 0,
      "TotalDeaths": 36,
      "NewRecovered": 0,
      "TotalRecovered": 1036,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Bhutan",
      "CountryCode": "BT",
      "Slug": "bhutan",
      "NewConfirmed": 1,
      "TotalConfirmed": 102,
      "NewDeaths": 0,
      "TotalDeaths": 0,
      "NewRecovered": 0,
      "TotalRecovered": 89,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Bolivia",
      "CountryCode": "BO",
      "Slug": "bolivia",
      "NewConfirmed": 2004,
      "TotalConfirmed": 78793,
      "NewDeaths": 87,
      "TotalDeaths": 3064,
      "NewRecovered": 386,
      "TotalRecovered": 23968,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Bosnia and Herzegovina",
      "CountryCode": "BA",
      "Slug": "bosnia-and-herzegovina",
      "NewConfirmed": 0,
      "TotalConfirmed": 11876,
      "NewDeaths": 0,
      "TotalDeaths": 339,
      "NewRecovered": 0,
      "TotalRecovered": 5959,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Botswana",
      "CountryCode": "BW",
      "Slug": "botswana",
      "NewConfirmed": 0,
      "TotalConfirmed": 804,
      "NewDeaths": 0,
      "TotalDeaths": 2,
      "NewRecovered": 0,
      "TotalRecovered": 63,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Brazil",
      "CountryCode": "BR",
      "Slug": "brazil",
      "NewConfirmed": 45392,
      "TotalConfirmed": 2707877,
      "NewDeaths": 1088,
      "TotalDeaths": 93563,
      "NewRecovered": 29128,
      "TotalRecovered": 2037982,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Brunei Darussalam",
      "CountryCode": "BN",
      "Slug": "brunei",
      "NewConfirmed": 0,
      "TotalConfirmed": 141,
      "NewDeaths": 0,
      "TotalDeaths": 3,
      "NewRecovered": 0,
      "TotalRecovered": 138,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Bulgaria",
      "CountryCode": "BG",
      "Slug": "bulgaria",
      "NewConfirmed": 146,
      "TotalConfirmed": 11836,
      "NewDeaths": 2,
      "TotalDeaths": 385,
      "NewRecovered": 77,
      "TotalRecovered": 6396,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Burkina Faso",
      "CountryCode": "BF",
      "Slug": "burkina-faso",
      "NewConfirmed": 37,
      "TotalConfirmed": 1143,
      "NewDeaths": 0,
      "TotalDeaths": 53,
      "NewRecovered": 0,
      "TotalRecovered": 935,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Burundi",
      "CountryCode": "BI",
      "Slug": "burundi",
      "NewConfirmed": 8,
      "TotalConfirmed": 395,
      "NewDeaths": 0,
      "TotalDeaths": 1,
      "NewRecovered": 0,
      "TotalRecovered": 304,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Cambodia",
      "CountryCode": "KH",
      "Slug": "cambodia",
      "NewConfirmed": 1,
      "TotalConfirmed": 240,
      "NewDeaths": 0,
      "TotalDeaths": 0,
      "NewRecovered": 32,
      "TotalRecovered": 196,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Cameroon",
      "CountryCode": "CM",
      "Slug": "cameroon",
      "NewConfirmed": 0,
      "TotalConfirmed": 17255,
      "NewDeaths": 0,
      "TotalDeaths": 391,
      "NewRecovered": 0,
      "TotalRecovered": 15320,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Canada",
      "CountryCode": "CA",
      "Slug": "canada",
      "NewConfirmed": 242,
      "TotalConfirmed": 118510,
      "NewDeaths": 6,
      "TotalDeaths": 8985,
      "NewRecovered": 166,
      "TotalRecovered": 103072,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Cape Verde",
      "CountryCode": "CV",
      "Slug": "cape-verde",
      "NewConfirmed": 29,
      "TotalConfirmed": 2480,
      "NewDeaths": 1,
      "TotalDeaths": 24,
      "NewRecovered": 13,
      "TotalRecovered": 1837,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Central African Republic",
      "CountryCode": "CF",
      "Slug": "central-african-republic",
      "NewConfirmed": 6,
      "TotalConfirmed": 4614,
      "NewDeaths": 0,
      "TotalDeaths": 59,
      "NewRecovered": 29,
      "TotalRecovered": 1635,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Chad",
      "CountryCode": "TD",
      "Slug": "chad",
      "NewConfirmed": 0,
      "TotalConfirmed": 936,
      "NewDeaths": 0,
      "TotalDeaths": 75,
      "NewRecovered": 0,
      "TotalRecovered": 813,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Chile",
      "CountryCode": "CL",
      "Slug": "chile",
      "NewConfirmed": 1991,
      "TotalConfirmed": 357658,
      "NewDeaths": 76,
      "TotalDeaths": 9533,
      "NewRecovered": 2180,
      "TotalRecovered": 330507,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "China",
      "CountryCode": "CN",
      "Slug": "china",
      "NewConfirmed": 172,
      "TotalConfirmed": 87827,
      "NewDeaths": 6,
      "TotalDeaths": 4667,
      "NewRecovered": 120,
      "TotalRecovered": 80907,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Colombia",
      "CountryCode": "CO",
      "Slug": "colombia",
      "NewConfirmed": 10673,
      "TotalConfirmed": 306181,
      "NewDeaths": 225,
      "TotalDeaths": 10330,
      "NewRecovered": 6321,
      "TotalRecovered": 160708,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Comoros",
      "CountryCode": "KM",
      "Slug": "comoros",
      "NewConfirmed": 8,
      "TotalConfirmed": 386,
      "NewDeaths": 0,
      "TotalDeaths": 7,
      "NewRecovered": 0,
      "TotalRecovered": 330,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Congo (Brazzaville)",
      "CountryCode": "CG",
      "Slug": "congo-brazzaville",
      "NewConfirmed": 0,
      "TotalConfirmed": 3200,
      "NewDeaths": 0,
      "TotalDeaths": 54,
      "NewRecovered": 0,
      "TotalRecovered": 829,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Congo (Kinshasa)",
      "CountryCode": "CD",
      "Slug": "congo-kinshasa",
      "NewConfirmed": 14,
      "TotalConfirmed": 9084,
      "NewDeaths": 0,
      "TotalDeaths": 215,
      "NewRecovered": 234,
      "TotalRecovered": 7030,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Costa Rica",
      "CountryCode": "CR",
      "Slug": "costa-rica",
      "NewConfirmed": 367,
      "TotalConfirmed": 18187,
      "NewDeaths": 4,
      "TotalDeaths": 154,
      "NewRecovered": 127,
      "TotalRecovered": 4531,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Croatia",
      "CountryCode": "HR",
      "Slug": "croatia",
      "NewConfirmed": 85,
      "TotalConfirmed": 5224,
      "NewDeaths": 0,
      "TotalDeaths": 145,
      "NewRecovered": 74,
      "TotalRecovered": 4341,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Cuba",
      "CountryCode": "CU",
      "Slug": "cuba",
      "NewConfirmed": 25,
      "TotalConfirmed": 2633,
      "NewDeaths": 0,
      "TotalDeaths": 87,
      "NewRecovered": 12,
      "TotalRecovered": 2367,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Cyprus",
      "CountryCode": "CY",
      "Slug": "cyprus",
      "NewConfirmed": 10,
      "TotalConfirmed": 1124,
      "NewDeaths": 0,
      "TotalDeaths": 19,
      "NewRecovered": 0,
      "TotalRecovered": 852,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Czech Republic",
      "CountryCode": "CZ",
      "Slug": "czech-republic",
      "NewConfirmed": 125,
      "TotalConfirmed": 16699,
      "NewDeaths": 1,
      "TotalDeaths": 383,
      "NewRecovered": 18,
      "TotalRecovered": 11587,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Côte d'Ivoire",
      "CountryCode": "CI",
      "Slug": "cote-divoire",
      "NewConfirmed": 62,
      "TotalConfirmed": 16109,
      "NewDeaths": 0,
      "TotalDeaths": 102,
      "NewRecovered": 322,
      "TotalRecovered": 11750,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Denmark",
      "CountryCode": "DK",
      "Slug": "denmark",
      "NewConfirmed": 0,
      "TotalConfirmed": 14028,
      "NewDeaths": 0,
      "TotalDeaths": 615,
      "NewRecovered": 0,
      "TotalRecovered": 12780,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Djibouti",
      "CountryCode": "DJ",
      "Slug": "djibouti",
      "NewConfirmed": 0,
      "TotalConfirmed": 5084,
      "NewDeaths": 0,
      "TotalDeaths": 58,
      "NewRecovered": 0,
      "TotalRecovered": 4999,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Dominica",
      "CountryCode": "DM",
      "Slug": "dominica",
      "NewConfirmed": 0,
      "TotalConfirmed": 18,
      "NewDeaths": 0,
      "TotalDeaths": 0,
      "NewRecovered": 0,
      "TotalRecovered": 18,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Dominican Republic",
      "CountryCode": "DO",
      "Slug": "dominican-republic",
      "NewConfirmed": 1766,
      "TotalConfirmed": 71415,
      "NewDeaths": 10,
      "TotalDeaths": 1170,
      "NewRecovered": 1039,
      "TotalRecovered": 37509,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Ecuador",
      "CountryCode": "EC",
      "Slug": "ecuador",
      "NewConfirmed": 877,
      "TotalConfirmed": 86232,
      "NewDeaths": 34,
      "TotalDeaths": 5736,
      "NewRecovered": 169,
      "TotalRecovered": 36213,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Egypt",
      "CountryCode": "EG",
      "Slug": "egypt",
      "NewConfirmed": 238,
      "TotalConfirmed": 94316,
      "NewDeaths": 29,
      "TotalDeaths": 4834,
      "NewRecovered": 1499,
      "TotalRecovered": 41137,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "El Salvador",
      "CountryCode": "SV",
      "Slug": "el-salvador",
      "NewConfirmed": 418,
      "TotalConfirmed": 17050,
      "NewDeaths": 11,
      "TotalDeaths": 459,
      "NewRecovered": 133,
      "TotalRecovered": 8495,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Equatorial Guinea",
      "CountryCode": "GQ",
      "Slug": "equatorial-guinea",
      "NewConfirmed": 0,
      "TotalConfirmed": 4821,
      "NewDeaths": 0,
      "TotalDeaths": 83,
      "NewRecovered": 0,
      "TotalRecovered": 2182,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Eritrea",
      "CountryCode": "ER",
      "Slug": "eritrea",
      "NewConfirmed": 0,
      "TotalConfirmed": 279,
      "NewDeaths": 0,
      "TotalDeaths": 0,
      "NewRecovered": 0,
      "TotalRecovered": 225,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Estonia",
      "CountryCode": "EE",
      "Slug": "estonia",
      "NewConfirmed": 8,
      "TotalConfirmed": 2072,
      "NewDeaths": 0,
      "TotalDeaths": 69,
      "NewRecovered": 4,
      "TotalRecovered": 1934,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Ethiopia",
      "CountryCode": "ET",
      "Slug": "ethiopia",
      "NewConfirmed": 469,
      "TotalConfirmed": 17999,
      "NewDeaths": 10,
      "TotalDeaths": 284,
      "NewRecovered": 245,
      "TotalRecovered": 7195,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Fiji",
      "CountryCode": "FJ",
      "Slug": "fiji",
      "NewConfirmed": 0,
      "TotalConfirmed": 27,
      "NewDeaths": 0,
      "TotalDeaths": 1,
      "NewRecovered": 0,
      "TotalRecovered": 18,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Finland",
      "CountryCode": "FI",
      "Slug": "finland",
      "NewConfirmed": 11,
      "TotalConfirmed": 7443,
      "NewDeaths": 0,
      "TotalDeaths": 329,
      "NewRecovered": 0,
      "TotalRecovered": 6950,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "France",
      "CountryCode": "FR",
      "Slug": "france",
      "NewConfirmed": 1,
      "TotalConfirmed": 225198,
      "NewDeaths": 0,
      "TotalDeaths": 30268,
      "NewRecovered": 0,
      "TotalRecovered": 81764,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Gabon",
      "CountryCode": "GA",
      "Slug": "gabon",
      "NewConfirmed": 179,
      "TotalConfirmed": 7531,
      "NewDeaths": 1,
      "TotalDeaths": 50,
      "NewRecovered": 280,
      "TotalRecovered": 5223,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Gambia",
      "CountryCode": "GM",
      "Slug": "gambia",
      "NewConfirmed": 0,
      "TotalConfirmed": 498,
      "NewDeaths": 0,
      "TotalDeaths": 9,
      "NewRecovered": 0,
      "TotalRecovered": 68,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Georgia",
      "CountryCode": "GE",
      "Slug": "georgia",
      "NewConfirmed": 3,
      "TotalConfirmed": 1171,
      "NewDeaths": 0,
      "TotalDeaths": 17,
      "NewRecovered": 7,
      "TotalRecovered": 947,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Germany",
      "CountryCode": "DE",
      "Slug": "germany",
      "NewConfirmed": 606,
      "TotalConfirmed": 211005,
      "NewDeaths": 7,
      "TotalDeaths": 9154,
      "NewRecovered": 644,
      "TotalRecovered": 192636,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Ghana",
      "CountryCode": "GH",
      "Slug": "ghana",
      "NewConfirmed": 1513,
      "TotalConfirmed": 37014,
      "NewDeaths": 0,
      "TotalDeaths": 182,
      "NewRecovered": 1269,
      "TotalRecovered": 33365,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Greece",
      "CountryCode": "GR",
      "Slug": "greece",
      "NewConfirmed": 110,
      "TotalConfirmed": 4587,
      "NewDeaths": 0,
      "TotalDeaths": 206,
      "NewRecovered": 0,
      "TotalRecovered": 1374,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Grenada",
      "CountryCode": "GD",
      "Slug": "grenada",
      "NewConfirmed": 0,
      "TotalConfirmed": 24,
      "NewDeaths": 0,
      "TotalDeaths": 0,
      "NewRecovered": 0,
      "TotalRecovered": 23,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Guatemala",
      "CountryCode": "GT",
      "Slug": "guatemala",
      "NewConfirmed": 1190,
      "TotalConfirmed": 50979,
      "NewDeaths": 35,
      "TotalDeaths": 1959,
      "NewRecovered": 1057,
      "TotalRecovered": 37873,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Guinea",
      "CountryCode": "GN",
      "Slug": "guinea",
      "NewConfirmed": 0,
      "TotalConfirmed": 7308,
      "NewDeaths": 0,
      "TotalDeaths": 46,
      "NewRecovered": 0,
      "TotalRecovered": 6458,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Guinea-Bissau",
      "CountryCode": "GW",
      "Slug": "guinea-bissau",
      "NewConfirmed": 0,
      "TotalConfirmed": 1981,
      "NewDeaths": 1,
      "TotalDeaths": 27,
      "NewRecovered": 0,
      "TotalRecovered": 803,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Guyana",
      "CountryCode": "GY",
      "Slug": "guyana",
      "NewConfirmed": 17,
      "TotalConfirmed": 430,
      "NewDeaths": 0,
      "TotalDeaths": 20,
      "NewRecovered": 0,
      "TotalRecovered": 185,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Haiti",
      "CountryCode": "HT",
      "Slug": "haiti",
      "NewConfirmed": 44,
      "TotalConfirmed": 7468,
      "NewDeaths": 4,
      "TotalDeaths": 165,
      "NewRecovered": 0,
      "TotalRecovered": 4606,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Holy See (Vatican City State)",
      "CountryCode": "VA",
      "Slug": "holy-see-vatican-city-state",
      "NewConfirmed": 0,
      "TotalConfirmed": 12,
      "NewDeaths": 0,
      "TotalDeaths": 0,
      "NewRecovered": 0,
      "TotalRecovered": 12,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Honduras",
      "CountryCode": "HN",
      "Slug": "honduras",
      "NewConfirmed": 671,
      "TotalConfirmed": 42685,
      "NewDeaths": 31,
      "TotalDeaths": 1368,
      "NewRecovered": 140,
      "TotalRecovered": 5694,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Hungary",
      "CountryCode": "HU",
      "Slug": "hungary",
      "NewConfirmed": 21,
      "TotalConfirmed": 4526,
      "NewDeaths": 1,
      "TotalDeaths": 597,
      "NewRecovered": 11,
      "TotalRecovered": 3364,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Iceland",
      "CountryCode": "IS",
      "Slug": "iceland",
      "NewConfirmed": 8,
      "TotalConfirmed": 1893,
      "NewDeaths": 0,
      "TotalDeaths": 10,
      "NewRecovered": 0,
      "TotalRecovered": 1825,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "India",
      "CountryCode": "IN",
      "Slug": "india",
      "NewConfirmed": 54735,
      "TotalConfirmed": 1750723,
      "NewDeaths": 853,
      "TotalDeaths": 37364,
      "NewRecovered": 51255,
      "TotalRecovered": 1145629,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Indonesia",
      "CountryCode": "ID",
      "Slug": "indonesia",
      "NewConfirmed": 1560,
      "TotalConfirmed": 109936,
      "NewDeaths": 62,
      "TotalDeaths": 5193,
      "NewRecovered": 2012,
      "TotalRecovered": 67919,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Iran, Islamic Republic of",
      "CountryCode": "IR",
      "Slug": "iran",
      "NewConfirmed": 2548,
      "TotalConfirmed": 306752,
      "NewDeaths": 216,
      "TotalDeaths": 16982,
      "NewRecovered": 2311,
      "TotalRecovered": 265830,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Iraq",
      "CountryCode": "IQ",
      "Slug": "iraq",
      "NewConfirmed": 2095,
      "TotalConfirmed": 126704,
      "NewDeaths": 64,
      "TotalDeaths": 4805,
      "NewRecovered": 1841,
      "TotalRecovered": 89275,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Ireland",
      "CountryCode": "IE",
      "Slug": "ireland",
      "NewConfirmed": 44,
      "TotalConfirmed": 26109,
      "NewDeaths": 0,
      "TotalDeaths": 1763,
      "NewRecovered": 0,
      "TotalRecovered": 23364,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Israel",
      "CountryCode": "IL",
      "Slug": "israel",
      "NewConfirmed": 1248,
      "TotalConfirmed": 72218,
      "NewDeaths": 14,
      "TotalDeaths": 526,
      "NewRecovered": 1252,
      "TotalRecovered": 45102,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Italy",
      "CountryCode": "IT",
      "Slug": "italy",
      "NewConfirmed": 295,
      "TotalConfirmed": 247832,
      "NewDeaths": 5,
      "TotalDeaths": 35146,
      "NewRecovered": 255,
      "TotalRecovered": 200229,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Jamaica",
      "CountryCode": "JM",
      "Slug": "jamaica",
      "NewConfirmed": 5,
      "TotalConfirmed": 883,
      "NewDeaths": 0,
      "TotalDeaths": 10,
      "NewRecovered": 17,
      "TotalRecovered": 743,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Japan",
      "CountryCode": "JP",
      "Slug": "japan",
      "NewConfirmed": 1570,
      "TotalConfirmed": 37804,
      "NewDeaths": 4,
      "TotalDeaths": 1012,
      "NewRecovered": 573,
      "TotalRecovered": 25347,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Jordan",
      "CountryCode": "JO",
      "Slug": "jordan",
      "NewConfirmed": 15,
      "TotalConfirmed": 1208,
      "NewDeaths": 0,
      "TotalDeaths": 11,
      "NewRecovered": 10,
      "TotalRecovered": 1094,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Kazakhstan",
      "CountryCode": "KZ",
      "Slug": "kazakhstan",
      "NewConfirmed": 0,
      "TotalConfirmed": 90367,
      "NewDeaths": 0,
      "TotalDeaths": 793,
      "NewRecovered": 0,
      "TotalRecovered": 60825,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Kenya",
      "CountryCode": "KE",
      "Slug": "kenya",
      "NewConfirmed": 727,
      "TotalConfirmed": 21363,
      "NewDeaths": 23,
      "TotalDeaths": 364,
      "NewRecovered": 254,
      "TotalRecovered": 8419,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Korea (South)",
      "CountryCode": "KR",
      "Slug": "korea-south",
      "NewConfirmed": 30,
      "TotalConfirmed": 14366,
      "NewDeaths": 0,
      "TotalDeaths": 301,
      "NewRecovered": 26,
      "TotalRecovered": 13259,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Kuwait",
      "CountryCode": "KW",
      "Slug": "kuwait",
      "NewConfirmed": 491,
      "TotalConfirmed": 67448,
      "NewDeaths": 6,
      "TotalDeaths": 453,
      "NewRecovered": 593,
      "TotalRecovered": 58525,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Kyrgyzstan",
      "CountryCode": "KG",
      "Slug": "kyrgyzstan",
      "NewConfirmed": 494,
      "TotalConfirmed": 36299,
      "NewDeaths": 19,
      "TotalDeaths": 1397,
      "NewRecovered": 1382,
      "TotalRecovered": 26419,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Lao PDR",
      "CountryCode": "LA",
      "Slug": "lao-pdr",
      "NewConfirmed": 0,
      "TotalConfirmed": 20,
      "NewDeaths": 0,
      "TotalDeaths": 0,
      "NewRecovered": 0,
      "TotalRecovered": 19,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Latvia",
      "CountryCode": "LV",
      "Slug": "latvia",
      "NewConfirmed": 7,
      "TotalConfirmed": 1238,
      "NewDeaths": 0,
      "TotalDeaths": 32,
      "NewRecovered": 0,
      "TotalRecovered": 1052,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Lebanon",
      "CountryCode": "LB",
      "Slug": "lebanon",
      "NewConfirmed": 175,
      "TotalConfirmed": 4730,
      "NewDeaths": 0,
      "TotalDeaths": 61,
      "NewRecovered": 0,
      "TotalRecovered": 1761,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Lesotho",
      "CountryCode": "LS",
      "Slug": "lesotho",
      "NewConfirmed": 98,
      "TotalConfirmed": 702,
      "NewDeaths": 1,
      "TotalDeaths": 14,
      "NewRecovered": 27,
      "TotalRecovered": 171,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Liberia",
      "CountryCode": "LR",
      "Slug": "liberia",
      "NewConfirmed": 3,
      "TotalConfirmed": 1189,
      "NewDeaths": 0,
      "TotalDeaths": 75,
      "NewRecovered": 3,
      "TotalRecovered": 673,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Libya",
      "CountryCode": "LY",
      "Slug": "libya",
      "NewConfirmed": 70,
      "TotalConfirmed": 3691,
      "NewDeaths": 6,
      "TotalDeaths": 80,
      "NewRecovered": 1,
      "TotalRecovered": 619,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Liechtenstein",
      "CountryCode": "LI",
      "Slug": "liechtenstein",
      "NewConfirmed": 0,
      "TotalConfirmed": 88,
      "NewDeaths": 0,
      "TotalDeaths": 1,
      "NewRecovered": 0,
      "TotalRecovered": 85,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Lithuania",
      "CountryCode": "LT",
      "Slug": "lithuania",
      "NewConfirmed": 18,
      "TotalConfirmed": 2093,
      "NewDeaths": 0,
      "TotalDeaths": 80,
      "NewRecovered": 0,
      "TotalRecovered": 1644,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Luxembourg",
      "CountryCode": "LU",
      "Slug": "luxembourg",
      "NewConfirmed": 98,
      "TotalConfirmed": 6793,
      "NewDeaths": 2,
      "TotalDeaths": 116,
      "NewRecovered": 0,
      "TotalRecovered": 5192,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Macedonia, Republic of",
      "CountryCode": "MK",
      "Slug": "macedonia",
      "NewConfirmed": 137,
      "TotalConfirmed": 10891,
      "NewDeaths": 7,
      "TotalDeaths": 493,
      "NewRecovered": 144,
      "TotalRecovered": 6698,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Madagascar",
      "CountryCode": "MG",
      "Slug": "madagascar",
      "NewConfirmed": 405,
      "TotalConfirmed": 11273,
      "NewDeaths": 1,
      "TotalDeaths": 107,
      "NewRecovered": 302,
      "TotalRecovered": 8109,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Malawi",
      "CountryCode": "MW",
      "Slug": "malawi",
      "NewConfirmed": 108,
      "TotalConfirmed": 4186,
      "NewDeaths": 6,
      "TotalDeaths": 120,
      "NewRecovered": 39,
      "TotalRecovered": 1914,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Malaysia",
      "CountryCode": "MY",
      "Slug": "malaysia",
      "NewConfirmed": 9,
      "TotalConfirmed": 8985,
      "NewDeaths": 0,
      "TotalDeaths": 125,
      "NewRecovered": 3,
      "TotalRecovered": 8647,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Maldives",
      "CountryCode": "MV",
      "Slug": "maldives",
      "NewConfirmed": 156,
      "TotalConfirmed": 3949,
      "NewDeaths": 1,
      "TotalDeaths": 17,
      "NewRecovered": 6,
      "TotalRecovered": 2613,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Mali",
      "CountryCode": "ML",
      "Slug": "mali",
      "NewConfirmed": 0,
      "TotalConfirmed": 2535,
      "NewDeaths": 0,
      "TotalDeaths": 124,
      "NewRecovered": 0,
      "TotalRecovered": 1937,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Malta",
      "CountryCode": "MT",
      "Slug": "malta",
      "NewConfirmed": 21,
      "TotalConfirmed": 845,
      "NewDeaths": 0,
      "TotalDeaths": 9,
      "NewRecovered": 0,
      "TotalRecovered": 665,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Mauritania",
      "CountryCode": "MR",
      "Slug": "mauritania",
      "NewConfirmed": 9,
      "TotalConfirmed": 6319,
      "NewDeaths": 0,
      "TotalDeaths": 157,
      "NewRecovered": 81,
      "TotalRecovered": 5043,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Mauritius",
      "CountryCode": "MU",
      "Slug": "mauritius",
      "NewConfirmed": 0,
      "TotalConfirmed": 344,
      "NewDeaths": 0,
      "TotalDeaths": 10,
      "NewRecovered": 0,
      "TotalRecovered": 332,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Mexico",
      "CountryCode": "MX",
      "Slug": "mexico",
      "NewConfirmed": 9556,
      "TotalConfirmed": 434193,
      "NewDeaths": 784,
      "TotalDeaths": 47472,
      "NewRecovered": 7752,
      "TotalRecovered": 334867,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Moldova",
      "CountryCode": "MD",
      "Slug": "moldova",
      "NewConfirmed": 380,
      "TotalConfirmed": 25113,
      "NewDeaths": 10,
      "TotalDeaths": 788,
      "NewRecovered": 302,
      "TotalRecovered": 17571,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Monaco",
      "CountryCode": "MC",
      "Slug": "monaco",
      "NewConfirmed": 0,
      "TotalConfirmed": 120,
      "NewDeaths": 0,
      "TotalDeaths": 4,
      "NewRecovered": 0,
      "TotalRecovered": 105,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Mongolia",
      "CountryCode": "MN",
      "Slug": "mongolia",
      "NewConfirmed": 2,
      "TotalConfirmed": 293,
      "NewDeaths": 0,
      "TotalDeaths": 0,
      "NewRecovered": 0,
      "TotalRecovered": 230,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Montenegro",
      "CountryCode": "ME",
      "Slug": "montenegro",
      "NewConfirmed": 125,
      "TotalConfirmed": 3198,
      "NewDeaths": 2,
      "TotalDeaths": 50,
      "NewRecovered": 288,
      "TotalRecovered": 1293,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Morocco",
      "CountryCode": "MA",
      "Slug": "morocco",
      "NewConfirmed": 693,
      "TotalConfirmed": 25015,
      "NewDeaths": 14,
      "TotalDeaths": 367,
      "NewRecovered": 302,
      "TotalRecovered": 17960,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Mozambique",
      "CountryCode": "MZ",
      "Slug": "mozambique",
      "NewConfirmed": 43,
      "TotalConfirmed": 1907,
      "NewDeaths": 1,
      "TotalDeaths": 12,
      "NewRecovered": 4,
      "TotalRecovered": 645,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Myanmar",
      "CountryCode": "MM",
      "Slug": "myanmar",
      "NewConfirmed": 0,
      "TotalConfirmed": 353,
      "NewDeaths": 0,
      "TotalDeaths": 6,
      "NewRecovered": 1,
      "TotalRecovered": 297,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Namibia",
      "CountryCode": "NA",
      "Slug": "namibia",
      "NewConfirmed": 95,
      "TotalConfirmed": 2224,
      "NewDeaths": 1,
      "TotalDeaths": 11,
      "NewRecovered": 5,
      "TotalRecovered": 171,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Nepal",
      "CountryCode": "NP",
      "Slug": "nepal",
      "NewConfirmed": 315,
      "TotalConfirmed": 20086,
      "NewDeaths": 0,
      "TotalDeaths": 56,
      "NewRecovered": 93,
      "TotalRecovered": 14492,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Netherlands",
      "CountryCode": "NL",
      "Slug": "netherlands",
      "NewConfirmed": 431,
      "TotalConfirmed": 55021,
      "NewDeaths": 1,
      "TotalDeaths": 6167,
      "NewRecovered": 0,
      "TotalRecovered": 200,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "New Zealand",
      "CountryCode": "NZ",
      "Slug": "new-zealand",
      "NewConfirmed": 3,
      "TotalConfirmed": 1565,
      "NewDeaths": 0,
      "TotalDeaths": 22,
      "NewRecovered": 0,
      "TotalRecovered": 1518,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Nicaragua",
      "CountryCode": "NI",
      "Slug": "nicaragua",
      "NewConfirmed": 0,
      "TotalConfirmed": 3672,
      "NewDeaths": 0,
      "TotalDeaths": 116,
      "NewRecovered": 0,
      "TotalRecovered": 2492,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Niger",
      "CountryCode": "NE",
      "Slug": "niger",
      "NewConfirmed": 2,
      "TotalConfirmed": 1136,
      "NewDeaths": 0,
      "TotalDeaths": 69,
      "NewRecovered": 0,
      "TotalRecovered": 1028,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Nigeria",
      "CountryCode": "NG",
      "Slug": "nigeria",
      "NewConfirmed": 386,
      "TotalConfirmed": 43537,
      "NewDeaths": 4,
      "TotalDeaths": 883,
      "NewRecovered": 522,
      "TotalRecovered": 20087,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Norway",
      "CountryCode": "NO",
      "Slug": "norway",
      "NewConfirmed": 13,
      "TotalConfirmed": 9253,
      "NewDeaths": 0,
      "TotalDeaths": 255,
      "NewRecovered": 0,
      "TotalRecovered": 8752,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Oman",
      "CountryCode": "OM",
      "Slug": "oman",
      "NewConfirmed": 0,
      "TotalConfirmed": 79159,
      "NewDeaths": 0,
      "TotalDeaths": 421,
      "NewRecovered": 0,
      "TotalRecovered": 61421,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Pakistan",
      "CountryCode": "PK",
      "Slug": "pakistan",
      "NewConfirmed": 0,
      "TotalConfirmed": 278305,
      "NewDeaths": 0,
      "TotalDeaths": 5951,
      "NewRecovered": 0,
      "TotalRecovered": 247177,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Palestinian Territory",
      "CountryCode": "PS",
      "Slug": "palestine",
      "NewConfirmed": 323,
      "TotalConfirmed": 12160,
      "NewDeaths": 1,
      "TotalDeaths": 83,
      "NewRecovered": 247,
      "TotalRecovered": 5324,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Panama",
      "CountryCode": "PA",
      "Slug": "panama",
      "NewConfirmed": 1127,
      "TotalConfirmed": 66383,
      "NewDeaths": 28,
      "TotalDeaths": 1449,
      "NewRecovered": 915,
      "TotalRecovered": 40081,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Papua New Guinea",
      "CountryCode": "PG",
      "Slug": "papua-new-guinea",
      "NewConfirmed": 19,
      "TotalConfirmed": 91,
      "NewDeaths": 0,
      "TotalDeaths": 2,
      "NewRecovered": 23,
      "TotalRecovered": 34,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Paraguay",
      "CountryCode": "PY",
      "Slug": "paraguay",
      "NewConfirmed": 147,
      "TotalConfirmed": 5485,
      "NewDeaths": 3,
      "TotalDeaths": 52,
      "NewRecovered": 238,
      "TotalRecovered": 3786,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Peru",
      "CountryCode": "PE",
      "Slug": "peru",
      "NewConfirmed": 0,
      "TotalConfirmed": 407492,
      "NewDeaths": 0,
      "TotalDeaths": 19021,
      "NewRecovered": 3212,
      "TotalRecovered": 287127,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Philippines",
      "CountryCode": "PH",
      "Slug": "philippines",
      "NewConfirmed": 12746,
      "TotalConfirmed": 98232,
      "NewDeaths": 77,
      "TotalDeaths": 2039,
      "NewRecovered": 38269,
      "TotalRecovered": 65265,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Poland",
      "CountryCode": "PL",
      "Slug": "poland",
      "NewConfirmed": 658,
      "TotalConfirmed": 46346,
      "NewDeaths": 5,
      "TotalDeaths": 1721,
      "NewRecovered": 387,
      "TotalRecovered": 34374,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Portugal",
      "CountryCode": "PT",
      "Slug": "portugal",
      "NewConfirmed": 238,
      "TotalConfirmed": 51310,
      "NewDeaths": 2,
      "TotalDeaths": 1737,
      "NewRecovered": 300,
      "TotalRecovered": 36783,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Qatar",
      "CountryCode": "QA",
      "Slug": "qatar",
      "NewConfirmed": 216,
      "TotalConfirmed": 110911,
      "NewDeaths": 0,
      "TotalDeaths": 174,
      "NewRecovered": 201,
      "TotalRecovered": 107578,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Republic of Kosovo",
      "CountryCode": "XK",
      "Slug": "kosovo",
      "NewConfirmed": 0,
      "TotalConfirmed": 8104,
      "NewDeaths": 0,
      "TotalDeaths": 212,
      "NewRecovered": 0,
      "TotalRecovered": 4463,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Romania",
      "CountryCode": "RO",
      "Slug": "romania",
      "NewConfirmed": 1225,
      "TotalConfirmed": 52111,
      "NewDeaths": 36,
      "TotalDeaths": 2379,
      "NewRecovered": 339,
      "TotalRecovered": 27346,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Russian Federation",
      "CountryCode": "RU",
      "Slug": "russia",
      "NewConfirmed": 5429,
      "TotalConfirmed": 843890,
      "NewDeaths": 95,
      "TotalDeaths": 14034,
      "NewRecovered": 8099,
      "TotalRecovered": 645316,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Rwanda",
      "CountryCode": "RW",
      "Slug": "rwanda",
      "NewConfirmed": 20,
      "TotalConfirmed": 2042,
      "NewDeaths": 0,
      "TotalDeaths": 5,
      "NewRecovered": 13,
      "TotalRecovered": 1119,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Saint Kitts and Nevis",
      "CountryCode": "KN",
      "Slug": "saint-kitts-and-nevis",
      "NewConfirmed": 0,
      "TotalConfirmed": 17,
      "NewDeaths": 0,
      "TotalDeaths": 0,
      "NewRecovered": 0,
      "TotalRecovered": 16,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Saint Lucia",
      "CountryCode": "LC",
      "Slug": "saint-lucia",
      "NewConfirmed": 0,
      "TotalConfirmed": 25,
      "NewDeaths": 0,
      "TotalDeaths": 0,
      "NewRecovered": 0,
      "TotalRecovered": 22,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Saint Vincent and Grenadines",
      "CountryCode": "VC",
      "Slug": "saint-vincent-and-the-grenadines",
      "NewConfirmed": 0,
      "TotalConfirmed": 54,
      "NewDeaths": 0,
      "TotalDeaths": 0,
      "NewRecovered": 0,
      "TotalRecovered": 44,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "San Marino",
      "CountryCode": "SM",
      "Slug": "san-marino",
      "NewConfirmed": 0,
      "TotalConfirmed": 699,
      "NewDeaths": 0,
      "TotalDeaths": 42,
      "NewRecovered": 0,
      "TotalRecovered": 657,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Sao Tome and Principe",
      "CountryCode": "ST",
      "Slug": "sao-tome-and-principe",
      "NewConfirmed": 3,
      "TotalConfirmed": 874,
      "NewDeaths": 0,
      "TotalDeaths": 15,
      "NewRecovered": 4,
      "TotalRecovered": 782,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Saudi Arabia",
      "CountryCode": "SA",
      "Slug": "saudi-arabia",
      "NewConfirmed": 1573,
      "TotalConfirmed": 277478,
      "NewDeaths": 21,
      "TotalDeaths": 2887,
      "NewRecovered": 1890,
      "TotalRecovered": 237548,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Senegal",
      "CountryCode": "SN",
      "Slug": "senegal",
      "NewConfirmed": 52,
      "TotalConfirmed": 10284,
      "NewDeaths": 4,
      "TotalDeaths": 209,
      "NewRecovered": 46,
      "TotalRecovered": 6822,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Serbia",
      "CountryCode": "RS",
      "Slug": "serbia",
      "NewConfirmed": 330,
      "TotalConfirmed": 25882,
      "NewDeaths": 9,
      "TotalDeaths": 582,
      "NewRecovered": 0,
      "TotalRecovered": 0,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Seychelles",
      "CountryCode": "SC",
      "Slug": "seychelles",
      "NewConfirmed": 0,
      "TotalConfirmed": 114,
      "NewDeaths": 0,
      "TotalDeaths": 0,
      "NewRecovered": 0,
      "TotalRecovered": 39,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Sierra Leone",
      "CountryCode": "SL",
      "Slug": "sierra-leone",
      "NewConfirmed": 0,
      "TotalConfirmed": 1823,
      "NewDeaths": 0,
      "TotalDeaths": 67,
      "NewRecovered": 0,
      "TotalRecovered": 1362,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Singapore",
      "CountryCode": "SG",
      "Slug": "singapore",
      "NewConfirmed": 307,
      "TotalConfirmed": 52512,
      "NewDeaths": 0,
      "TotalDeaths": 27,
      "NewRecovered": 249,
      "TotalRecovered": 46740,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Slovakia",
      "CountryCode": "SK",
      "Slug": "slovakia",
      "NewConfirmed": 45,
      "TotalConfirmed": 2337,
      "NewDeaths": 0,
      "TotalDeaths": 29,
      "NewRecovered": 47,
      "TotalRecovered": 1742,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Slovenia",
      "CountryCode": "SI",
      "Slug": "slovenia",
      "NewConfirmed": 15,
      "TotalConfirmed": 2171,
      "NewDeaths": 0,
      "TotalDeaths": 119,
      "NewRecovered": 24,
      "TotalRecovered": 1821,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Somalia",
      "CountryCode": "SO",
      "Slug": "somalia",
      "NewConfirmed": 0,
      "TotalConfirmed": 3212,
      "NewDeaths": 0,
      "TotalDeaths": 93,
      "NewRecovered": 0,
      "TotalRecovered": 1562,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "South Africa",
      "CountryCode": "ZA",
      "Slug": "south-africa",
      "NewConfirmed": 10107,
      "TotalConfirmed": 503290,
      "NewDeaths": 148,
      "TotalDeaths": 8153,
      "NewRecovered": 16290,
      "TotalRecovered": 342461,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "South Sudan",
      "CountryCode": "SS",
      "Slug": "south-sudan",
      "NewConfirmed": 30,
      "TotalConfirmed": 2352,
      "NewDeaths": 0,
      "TotalDeaths": 46,
      "NewRecovered": 0,
      "TotalRecovered": 1175,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Spain",
      "CountryCode": "ES",
      "Slug": "spain",
      "NewConfirmed": 0,
      "TotalConfirmed": 288522,
      "NewDeaths": 0,
      "TotalDeaths": 28445,
      "NewRecovered": 0,
      "TotalRecovered": 150376,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Sri Lanka",
      "CountryCode": "LK",
      "Slug": "sri-lanka",
      "NewConfirmed": 0,
      "TotalConfirmed": 2815,
      "NewDeaths": 0,
      "TotalDeaths": 11,
      "NewRecovered": 48,
      "TotalRecovered": 2439,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Sudan",
      "CountryCode": "SD",
      "Slug": "sudan",
      "NewConfirmed": 94,
      "TotalConfirmed": 11738,
      "NewDeaths": 6,
      "TotalDeaths": 752,
      "NewRecovered": 18,
      "TotalRecovered": 6137,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Suriname",
      "CountryCode": "SR",
      "Slug": "suriname",
      "NewConfirmed": 110,
      "TotalConfirmed": 1760,
      "NewDeaths": 0,
      "TotalDeaths": 26,
      "NewRecovered": 81,
      "TotalRecovered": 1161,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Swaziland",
      "CountryCode": "SZ",
      "Slug": "swaziland",
      "NewConfirmed": 58,
      "TotalConfirmed": 2706,
      "NewDeaths": 2,
      "TotalDeaths": 43,
      "NewRecovered": 0,
      "TotalRecovered": 1214,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Sweden",
      "CountryCode": "SE",
      "Slug": "sweden",
      "NewConfirmed": 0,
      "TotalConfirmed": 80422,
      "NewDeaths": 0,
      "TotalDeaths": 5743,
      "NewRecovered": 0,
      "TotalRecovered": 0,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Switzerland",
      "CountryCode": "CH",
      "Slug": "switzerland",
      "NewConfirmed": 180,
      "TotalConfirmed": 35412,
      "NewDeaths": 0,
      "TotalDeaths": 1981,
      "NewRecovered": 200,
      "TotalRecovered": 31300,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Syrian Arab Republic (Syria)",
      "CountryCode": "SY",
      "Slug": "syria",
      "NewConfirmed": 23,
      "TotalConfirmed": 780,
      "NewDeaths": 0,
      "TotalDeaths": 43,
      "NewRecovered": 0,
      "TotalRecovered": 237,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Taiwan, Republic of China",
      "CountryCode": "TW",
      "Slug": "taiwan",
      "NewConfirmed": 7,
      "TotalConfirmed": 474,
      "NewDeaths": 0,
      "TotalDeaths": 7,
      "NewRecovered": 1,
      "TotalRecovered": 441,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Tajikistan",
      "CountryCode": "TJ",
      "Slug": "tajikistan",
      "NewConfirmed": 42,
      "TotalConfirmed": 7451,
      "NewDeaths": 0,
      "TotalDeaths": 60,
      "NewRecovered": 40,
      "TotalRecovered": 6233,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Tanzania, United Republic of",
      "CountryCode": "TZ",
      "Slug": "tanzania",
      "NewConfirmed": 0,
      "TotalConfirmed": 509,
      "NewDeaths": 0,
      "TotalDeaths": 21,
      "NewRecovered": 0,
      "TotalRecovered": 183,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Thailand",
      "CountryCode": "TH",
      "Slug": "thailand",
      "NewConfirmed": 2,
      "TotalConfirmed": 3312,
      "NewDeaths": 0,
      "TotalDeaths": 58,
      "NewRecovered": 10,
      "TotalRecovered": 3135,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Timor-Leste",
      "CountryCode": "TL",
      "Slug": "timor-leste",
      "NewConfirmed": 0,
      "TotalConfirmed": 24,
      "NewDeaths": 0,
      "TotalDeaths": 0,
      "NewRecovered": 0,
      "TotalRecovered": 24,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Togo",
      "CountryCode": "TG",
      "Slug": "togo",
      "NewConfirmed": 17,
      "TotalConfirmed": 958,
      "NewDeaths": 0,
      "TotalDeaths": 19,
      "NewRecovered": 6,
      "TotalRecovered": 647,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Trinidad and Tobago",
      "CountryCode": "TT",
      "Slug": "trinidad-and-tobago",
      "NewConfirmed": 4,
      "TotalConfirmed": 173,
      "NewDeaths": 0,
      "TotalDeaths": 8,
      "NewRecovered": 0,
      "TotalRecovered": 132,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Tunisia",
      "CountryCode": "TN",
      "Slug": "tunisia",
      "NewConfirmed": 17,
      "TotalConfirmed": 1552,
      "NewDeaths": 1,
      "TotalDeaths": 51,
      "NewRecovered": 22,
      "TotalRecovered": 1217,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Turkey",
      "CountryCode": "TR",
      "Slug": "turkey",
      "NewConfirmed": 996,
      "TotalConfirmed": 231869,
      "NewDeaths": 19,
      "TotalDeaths": 5710,
      "NewRecovered": 981,
      "TotalRecovered": 215516,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Uganda",
      "CountryCode": "UG",
      "Slug": "uganda",
      "NewConfirmed": 22,
      "TotalConfirmed": 1176,
      "NewDeaths": 1,
      "TotalDeaths": 4,
      "NewRecovered": 17,
      "TotalRecovered": 1045,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Ukraine",
      "CountryCode": "UA",
      "Slug": "ukraine",
      "NewConfirmed": 1205,
      "TotalConfirmed": 72609,
      "NewDeaths": 16,
      "TotalDeaths": 1733,
      "NewRecovered": 571,
      "TotalRecovered": 40516,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "United Arab Emirates",
      "CountryCode": "AE",
      "Slug": "united-arab-emirates",
      "NewConfirmed": 254,
      "TotalConfirmed": 60760,
      "NewDeaths": 0,
      "TotalDeaths": 351,
      "NewRecovered": 346,
      "TotalRecovered": 54255,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "United Kingdom",
      "CountryCode": "GB",
      "Slug": "united-kingdom",
      "NewConfirmed": 769,
      "TotalConfirmed": 305562,
      "NewDeaths": 74,
      "TotalDeaths": 46278,
      "NewRecovered": 2,
      "TotalRecovered": 1441,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "United States of America",
      "CountryCode": "US",
      "Slug": "united-states",
      "NewConfirmed": 58406,
      "TotalConfirmed": 4620444,
      "NewDeaths": 1133,
      "TotalDeaths": 154447,
      "NewRecovered": 23725,
      "TotalRecovered": 1461885,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Uruguay",
      "CountryCode": "UY",
      "Slug": "uruguay",
      "NewConfirmed": 14,
      "TotalConfirmed": 1278,
      "NewDeaths": 0,
      "TotalDeaths": 35,
      "NewRecovered": 10,
      "TotalRecovered": 1004,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Uzbekistan",
      "CountryCode": "UZ",
      "Slug": "uzbekistan",
      "NewConfirmed": 774,
      "TotalConfirmed": 24783,
      "NewDeaths": 6,
      "TotalDeaths": 147,
      "NewRecovered": 835,
      "TotalRecovered": 15299,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Venezuela (Bolivarian Republic)",
      "CountryCode": "VE",
      "Slug": "venezuela",
      "NewConfirmed": 869,
      "TotalConfirmed": 19443,
      "NewDeaths": 5,
      "TotalDeaths": 169,
      "NewRecovered": 708,
      "TotalRecovered": 11129,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Viet Nam",
      "CountryCode": "VN",
      "Slug": "vietnam",
      "NewConfirmed": 32,
      "TotalConfirmed": 590,
      "NewDeaths": 0,
      "TotalDeaths": 3,
      "NewRecovered": 0,
      "TotalRecovered": 373,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Western Sahara",
      "CountryCode": "EH",
      "Slug": "western-sahara",
      "NewConfirmed": 0,
      "TotalConfirmed": 10,
      "NewDeaths": 0,
      "TotalDeaths": 1,
      "NewRecovered": 0,
      "TotalRecovered": 8,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Yemen",
      "CountryCode": "YE",
      "Slug": "yemen",
      "NewConfirmed": 2,
      "TotalConfirmed": 1730,
      "NewDeaths": 1,
      "TotalDeaths": 494,
      "NewRecovered": 0,
      "TotalRecovered": 862,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Zambia",
      "CountryCode": "ZM",
      "Slug": "zambia",
      "NewConfirmed": 265,
      "TotalConfirmed": 6228,
      "NewDeaths": 14,
      "TotalDeaths": 165,
      "NewRecovered": 327,
      "TotalRecovered": 4130,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    },
    {
      "Country": "Zimbabwe",
      "CountryCode": "ZW",
      "Slug": "zimbabwe",
      "NewConfirmed": 490,
      "TotalConfirmed": 3659,
      "NewDeaths": 2,
      "TotalDeaths": 69,
      "NewRecovered": 7,
      "TotalRecovered": 1011,
      "Date": "2020-08-02T05:18:15Z",
      "Premium": {}
    }
  ],
  "Date": "2020-08-02T05:18:15Z"
};